import { notFound } from 'next/navigation'
import { Badge, Button, Card } from '@/components/ui'
import { PageHeader } from '@/components/dashboard/PageHeader'
import { importOrders } from '@/lib/api'
import { requireUser } from '@/lib/session'
import { acceptAgreementAction } from './actions'
import { PaymentProofForm } from './PaymentProofForm'

const money=(v:unknown)=>`${new Intl.NumberFormat('en-RW').format(Number(v||0))} RWF`
export default async function ImportOrderPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const{token}=await requireUser();const order=await importOrders.get(token,id).catch(()=>null);if(!order)notFound();const agreement=order.agreements?.[0];return <><PageHeader title={`${order.year||''} ${order.make} ${order.model}`} description={`${order.order_ref} · Importing from ${order.origin_country}`}/><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
  <div className="space-y-5"><Card className="p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-caption font-extrabold uppercase tracking-widest text-brand">Current milestone</p><h2 className="mt-2 text-2xl font-black text-content">{order.status.replaceAll('_',' ')}</h2></div><Badge tone="info">{order.order_ref}</Badge></div>{order.quoted_total_rwf?<p className="mt-5 text-3xl font-black text-content">{money(order.quoted_total_rwf)}</p>:null}</Card>
  {agreement&&!agreement.accepted_at?<Card className="p-6"><h2 className="text-xl font-black text-content">Import agreement</h2><p className="mt-3 text-body leading-relaxed text-content-secondary">Total: {money(agreement.terms_snapshot.quoted_total_rwf)}. First 50%: {money(agreement.terms_snapshot.initial_payment_rwf)}. Final 50%: {money(agreement.terms_snapshot.final_payment_rwf)}.</p><p className="mt-3 text-label text-content-secondary">{agreement.terms_snapshot.terms}</p><form action={acceptAgreementAction.bind(null,id)}><Button type="submit" className="mt-5">Accept agreement and continue</Button></form></Card>:null}
  <Card className="p-6"><h2 className="text-xl font-black text-content">Payments</h2>{order.payments.map((p:any)=><div key={p.id} className="mt-4 border-t border-line-soft pt-4"><div className="flex justify-between gap-3"><div><p className="font-extrabold text-content">{p.milestone.replaceAll('_',' ')}</p><p className="text-caption text-content-muted">{p.status}</p></div><p className="font-black text-content">{money(p.amount_rwf)}</p></div>{['due','rejected'].includes(p.status)&&order.agreement_accepted_at?<PaymentProofForm orderId={id} paymentId={p.id}/>:null}</div>)}</Card></div>
  <div className="space-y-5"><Card className="p-6"><h2 className="font-black text-content">Shipment</h2>{order.shipment?<dl className="mt-4 space-y-3 text-label">{[['Carrier',order.shipment.carrier],['Booking reference',order.shipment.booking_reference],['Last location',order.shipment.last_location],['Estimated arrival',order.shipment.estimated_arrival&&new Date(order.shipment.estimated_arrival).toLocaleString()]].filter(([,v])=>v).map(([k,v])=><div key={k} className="flex justify-between gap-3"><dt className="text-content-muted">{k}</dt><dd className="font-bold text-content">{v}</dd></div>)}</dl>:<p className="mt-3 text-label text-content-muted">Shipping details appear after the vehicle is purchased.</p>}</Card><Card className="p-6"><h2 className="font-black text-content">Timeline</h2><ol className="mt-4 space-y-4">{order.events.map((e:any)=><li key={e.id} className="border-l-2 border-brand/20 pl-4"><p className="font-bold text-content">{e.summary}</p><p className="text-caption text-content-muted">{new Date(e.created_at).toLocaleString()}</p></li>)}</ol></Card></div>
  </div></>}
