'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { api } from '@/lib/api'
import { Card, EmptyState, PageHeader, Pill } from '@/components/ui'

// The contract register. Every number ever allocated, newest first — including
// the ones that were superseded, voided, or never produced a file. That is the
// point: a numbered series with a hole in it is worthless as evidence, so the
// register shows the whole series rather than the currently-valid subset.

interface ContractRow {
  id: string
  contract_number: string
  status: 'draft' | 'issued' | 'signed' | 'superseded' | 'void'
  page_count: number | null
  generated_at: string
  issued_at: string | null
  signed_at: string | null
  draft_watermark: boolean
  void_reason: string | null
  handover_id: string
  booking_id: string | null
  make: string | null
  model: string | null
  year: string | null
  seller_name: string | null
  buyer_name: string | null
  generated_by_name: string | null
}

const PAGE = 100

const fileHref = (id: string, download = false) =>
  `/api/backend/contracts/${id}/file${download ? '?download=1' : ''}`

export default function ContractsPage() {
  const [rows, setRows]       = useState<ContractRow[]>([])
  const [offset, setOffset]   = useState(0)
  const [more, setMore]       = useState(false)
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState('')

  async function load(off = 0) {
    setLoading(true)
    try {
      const data = await api.contracts({ limit: String(PAGE), offset: String(off) })
      setRows((prev) => (off === 0 ? (data as ContractRow[]) : [...prev, ...(data as ContractRow[])]))
      setMore(data.length === PAGE)
      setOffset(off)
      setError('')
    } catch (e: any) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load(0) }, [])

  const counts = rows.reduce<Record<string, number>>((acc, c) => {
    acc[c.status] = (acc[c.status] || 0) + 1
    return acc
  }, {})

  return (
    <div>
      <PageHeader
        title="Contract register"
        description="Every sale agreement ever issued, newest first."
      />

      <div className="mb-6 rounded-lg border border-line bg-surface-alt p-4 text-sm text-content-secondary">
        <p className="font-bold text-content">This register is intentionally gap-free.</p>
        <p className="mt-1">
          A contract number is allocated inside the same transaction that stores the contract, so the
          series can never skip. Numbers are never reused and rows are never deleted: a contract that
          was replaced stays here as <span className="font-semibold">superseded</span> with the reason,
          a <span className="font-semibold">void</span> number stays spent, and a{' '}
          <span className="font-semibold">draft</span> is a number whose PDF never got written. If a
          number is missing from this list, something is wrong — that is what makes the list evidence.
        </p>
        {rows.length > 0 && (
          <p className="mt-2 text-xs text-content-muted">
            {rows.length} number{rows.length === 1 ? '' : 's'} shown
            {Object.keys(counts).length > 0 && ' · '}
            {(['signed', 'issued', 'draft', 'superseded', 'void'] as const)
              .filter((s) => counts[s])
              .map((s) => `${counts[s]} ${s}`)
              .join(' · ')}
          </p>
        )}
      </div>

      {error && <div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">Error: {error}</div>}

      {loading && rows.length === 0 ? (
        <div className="text-sm text-gray-400">Loading…</div>
      ) : rows.length === 0 ? (
        <Card>
          <EmptyState
            icon="document"
            title="No contracts issued yet"
            description="A sale agreement is generated from a confirmed handover — open one and choose Contract."
          />
        </Card>
      ) : (
        <>
          <div className="overflow-x-auto rounded-xl border border-gray-100 bg-white shadow-sm">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 text-left text-xs text-gray-500">
                  <th className="px-4 py-3 font-medium">Number</th>
                  <th className="px-4 py-3 font-medium">Status</th>
                  <th className="px-4 py-3 font-medium">Vehicle</th>
                  <th className="px-4 py-3 font-medium">Parties</th>
                  <th className="px-4 py-3 font-medium">Pages</th>
                  <th className="px-4 py-3 font-medium">Generated by</th>
                  <th className="px-4 py-3 font-medium">Dates</th>
                  <th className="px-4 py-3 text-right font-medium">File</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((c) => (
                  <tr key={c.id} className="border-b border-gray-50 align-top last:border-0">
                    <td className="whitespace-nowrap px-4 py-3">
                      <Link
                        href={`/handovers/${c.handover_id}/contract`}
                        className="font-mono font-medium text-gray-900 hover:text-brand hover:underline"
                      >
                        {c.contract_number}
                      </Link>
                      <p className="text-xs text-gray-500">{c.booking_id || '—'}</p>
                    </td>
                    <td className="px-4 py-3">
                      <Pill status={c.status} />
                      {c.draft_watermark && (
                        <p className="mt-1 text-[11px] font-semibold text-amber-700">DRAFT watermark</p>
                      )}
                    </td>
                    <td className="px-4 py-3">
                      <p className="font-medium text-gray-900">
                        {[c.year, c.make, c.model].filter(Boolean).join(' ') || '—'}
                      </p>
                    </td>
                    <td className="px-4 py-3 text-gray-600">
                      <p>{c.seller_name || '—'}</p>
                      <p className="text-xs text-gray-500">buyer: {c.buyer_name || '—'}</p>
                    </td>
                    <td className="px-4 py-3 text-gray-500">{c.page_count ?? '—'}</td>
                    <td className="px-4 py-3 text-gray-600">{c.generated_by_name || '—'}</td>
                    <td className="whitespace-nowrap px-4 py-3 text-xs text-gray-500">
                      <p>gen {new Date(c.generated_at).toLocaleDateString()}</p>
                      {c.issued_at && <p>issued {new Date(c.issued_at).toLocaleDateString()}</p>}
                      {c.signed_at && <p className="text-green-700">signed {new Date(c.signed_at).toLocaleDateString()}</p>}
                      {c.void_reason && (
                        <p className="mt-1 max-w-xs whitespace-normal italic text-gray-400">{c.void_reason}</p>
                      )}
                    </td>
                    <td className="whitespace-nowrap px-4 py-3 text-right">
                      {c.status === 'draft' ? (
                        <span className="text-xs text-gray-400">no file</span>
                      ) : (
                        <div className="flex justify-end gap-1.5">
                          <a
                            href={fileHref(c.id)}
                            target="_blank"
                            rel="noreferrer"
                            className="rounded-lg bg-gray-900 px-2 py-1 text-xs font-medium text-white hover:bg-gray-700"
                          >
                            Open
                          </a>
                          <a
                            href={fileHref(c.id, true)}
                            target="_blank"
                            rel="noreferrer"
                            className="rounded-lg bg-gray-100 px-2 py-1 text-xs font-medium text-gray-600 hover:bg-gray-200"
                          >
                            Download
                          </a>
                        </div>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {more && (
            <div className="mt-4 flex justify-center">
              <button
                onClick={() => load(offset + PAGE)}
                disabled={loading}
                className="rounded-lg border border-gray-200 bg-white px-4 py-2 text-sm font-semibold text-gray-600 hover:border-brand disabled:opacity-50"
              >
                {loading ? 'Loading…' : `Load the next ${PAGE}`}
              </button>
            </div>
          )}
        </>
      )}
    </div>
  )
}
