# scripts/update_all_dicts.py
"""
Enrich and synchronize all 6 language dictionaries with 100% key parity:
English (en), Kinyarwanda (rw), French (fr), Swahili (sw), Korean (ko), Chinese (zh).
"""
import sys, os, pprint

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'i18n_data'))

from dict_en import DICT_EN
from dict_rw import DICT_RW
from dict_fr import DICT_FR
from dict_sw import DICT_SW
from dict_ko import DICT_KO
from dict_zh import DICT_ZH

# New sections and keys with pure, natural, high-quality translations
ADDITIONS = {
    'en': {
        'rentalDetail': {
            'seats': 'Seats',
            'gearbox': 'Gearbox',
            'fuel': 'Fuel',
            'year': 'Year',
            'notFoundTitle': 'Rental Vehicle Not Found',
            'notFoundSub': 'This rental listing may have expired or is currently unavailable.',
            'goBack': 'Go Back',
            'loading': 'Loading rental details…',
            'share': 'Share rental',
            'shareMessage': 'Check out this rental on Sawa Cars: {{title}} at {{price}}',
            'forRent': 'For Rent',
            'certified': 'Certified {{score}}/150',
            'safariReady': 'Safari Ready',
            'unavailableUntil': 'Unavailable until {{date}}',
            'availability': 'Availability & Booking',
            'requestDates': 'Request Rental Dates',
            'availabilityNote': 'Availability is verified and confirmed directly by the independent rental provider.',
            'pricing': 'Rental Rates',
            'dailyRate': 'Daily Rate',
            'weeklyRate': 'Weekly Rate (7+ days)',
            'saveVsDaily': 'Save {{amount}} vs daily rate',
            'securityDeposit': 'Refundable Security Deposit',
            'depositSub': 'Paid directly to the provider at vehicle pickup and refunded after return check.',
            'minRental': 'Minimum rental duration is {{count}} days.',
            'confirmTerms': 'Rental Inclusions & Terms',
            'insurance': 'Comprehensive insurance cover included',
            'roadside': '24/7 Roadside breakdown assistance',
            'mileageLimits': 'Generous daily mileage allowance',
            'depositTerms': 'Clear and transparent deposit refund terms',
            'safetyLink': 'Read our marketplace safety & provider standards',
            'inspectionTitle': '150-Point Technical Inspection',
            'inspectionSub': 'Certified score: {{score}}/150 • Full condition verified',
            'howItWorks': 'How Renting Works',
            'step1Title': '1. Select Dates & Inquire',
            'step1Desc': 'Pick your preferred rental duration and send a direct availability inquiry to the provider.',
            'step2Title': '2. Confirm Terms & Inspect',
            'step2Desc': 'Meet the provider, review the digital walkaround check-in report and confirm the rental agreement.',
            'step3Title': '3. Drive & Return Smoothly',
            'step3Desc': 'Enjoy your trip across Rwanda. Upon return, complete the return check-out to release your deposit.',
            'ctaDailyRental': 'Daily Rental',
            'ctaPerDay': '/day',
            'ctaRateNote': 'Fuel & deposit extra',
            'ctaInquiryOnly': 'Direct Provider Request',
            'ctaRequestAvailability': 'Request Availability',
        },
        'dutyCalculator': {
            'title': 'Import Duty Calculator',
            'introTitle': 'Rwanda RRA Import Duty',
            'introSub': 'Most cars in Rwanda are imported. This calculator estimates the total duty payable to Rwanda Revenue Authority.',
            'lastReviewed': 'Rates last reviewed {{date}}.',
            'vehicleValue': 'Vehicle value (RWF)',
            'valuePlaceholder': 'e.g. 20000000',
            'valueHint': 'Enter the vehicle purchase price (FOB or CIF value)',
            'engineDisplacement': 'Engine displacement',
            'vehicleAge': 'Vehicle age',
            'calcBtn': 'Calculate Import Duty',
            'dutyBreakdown': 'Duty Breakdown',
            'vehicleSummary': '{{val}} vehicle',
            'assessedValue': 'Value assessed for duty (−{{pct}}% for age)',
            'cifValue': 'CIF Value (assessed value + freight + insurance)',
            'dutiesApplied': 'DUTIES APPLIED',
            'customsDuty': 'Customs Duty (25% of CIF)',
            'exciseDuty': 'Excise Duty ({{rate}}% of CIF + customs)',
            'vat': 'VAT — {{rate}}% (on CIF + duties)',
            'withholdingTax': 'Withholding Tax ({{rate}}% of CIF)',
            'infraLevy': 'Infrastructure Levy ({{rate}}% of CIF)',
            'totalDuties': 'Total Duties',
            'grandTotal': 'Grand Total (vehicle + duties)',
            'effectiveRate': 'Effective duty rate',
            'effectiveRateDesc': 'Of the {{val}} vehicle value, {{rate}}% is added as import duty when bringing this car into Rwanda.',
            'estimatedLandedCost': 'Estimated landed cost',
            'rwfNote': 'All figures are shown in Rwandan francs',
            'disclaimer': 'This is an estimate based on standard 2026 Rwanda Revenue Authority rates. Actual duty may vary based on the vehicle\'s age, import origin, and RRA assessment. Consult a licensed clearing agent for a precise figure.',
            'ageUnder2': 'Under 2 years',
            'age2to4': '2 – 4 years',
            'age4to6': '4 – 6 years',
            'age6to8': '6 – 8 years',
            'age8to10': '8 – 10 years',
            'ageOver10': 'Over 10 years',
            'ccCity': 'City cars, small hatchbacks',
            'ccSedan': 'Most sedans, crossovers',
            'ccSuv': 'Mid-size SUVs, luxury, V8+',
            'exciseBadge': 'Excise {{rate}}',
        },
        'financing': {
            'title': 'Financing Calculator',
            'introTitle': 'Estimate monthly payments',
            'introSub': 'Based on Rwanda commercial bank auto loan rates for 2026. Actual rates may vary — contact your bank for a formal quote.',
            'carPrice': 'Car price (RWF)',
            'carPricePlaceholder': 'e.g. 24000000',
            'downPayment': 'Down payment (RWF)',
            'downPaymentPlaceholder': 'e.g. 5000000 (20%)',
            'loanAmount': 'Loan amount',
            'loanTerm': 'Loan term',
            'compareBanks': 'Compare banks',
            'sortedByRate': 'sorted by rate',
            'lowestRate': 'Lowest rate',
            'perYear': 'per year',
            'monthly': 'Monthly',
            'totalInterest': 'Total interest',
            'totalRepaid': 'Total repaid',
            'yourEstimate': 'Your estimate · {{bank}}',
            'annualRate': 'Annual rate',
            'monthlyPayment': 'Monthly payment',
            'months': '{{count}} months ({{years}}yr)',
            'disclaimer': 'This is a rough estimate only. Actual rates, fees and eligibility depend on your credit profile, bank policies, and the specific vehicle. Contact your bank for a formal auto loan quote. Sawa Cars does not facilitate loans.',
            'bankBKNote': 'Rwanda\'s largest bank',
            'bankEquityNote': 'Pan-African network',
            'bankIMNote': 'Competitive auto rates',
            'bankKCBNote': 'East Africa\'s top bank',
        },
        'carValuation': {
            'title': 'What\'s My Car Worth?',
            'lede': 'Get an instant market estimate — free, no account needed. Takes 30 seconds.',
            'make': 'Make',
            'makePlaceholder': 'Type the make, e.g. Peugeot',
            'otherBrand': 'Other brand',
            'model': 'Model (optional)',
            'modelPlaceholder': 'e.g. RAV4, Civic, Forester',
            'year': 'Year',
            'mileage': 'Mileage (km)',
            'mileagePlaceholder': 'e.g. 45000',
            'checkingMarket': 'Checking the market…',
            'getValuation': 'Get My Valuation',
            'fillRequired': 'Fill in make, year & mileage',
            'noAccountRequired': 'No account required. We never share your details.',
            'yourValuation': 'Your Valuation',
            'estimatedMarketValue': 'ESTIMATED MARKET VALUE',
            'basedOnComparables': 'Based on {{count}} similar {{make}} cars on Sawa Cars',
            'basedOnMarket': 'Based on current Kigali market data',
            'getCertifiedPrice': 'Get the certified price',
            'certifiedPriceSub': 'Cars that pass our 150-point inspection sell for up to 12% more — and 3× faster. The inspection is the listing.',
            'step1': 'Book a free inspection slot at any Sawa center',
            'step2': 'Pass the 150-point check — we photograph & list it',
            'step3': 'Meet verified buyers, hand over at our center',
            'submitForInspection': 'Submit for Inspection',
            'valueAnotherCar': 'Value a different car',
            'notEnoughData': 'We couldn\'t estimate right now — not enough market data. Check your connection and try again.',
        },
    },
    'rw': {
        'rentalDetail': {
            'seats': 'Imyanya',
            'gearbox': 'Ububiko bw\'umuvuduko',
            'fuel': 'Lisansi/Maziwa',
            'year': 'Umwaka',
            'notFoundTitle': 'Imodoka yo Gukodesha Ntibonetse',
            'notFoundSub': 'Iri tangazo ryo gukodesha rishobora kuba ryararangiye cyangwa ntiriboneka muri iki gihe.',
            'goBack': 'Subira Inyuma',
            'loading': 'Gushyiraho amakuru y\'imodoka ikodeshwa…',
            'share': 'Sangiza imodoka ikodeshwa',
            'shareMessage': 'Reba iyi modoka ikodeshwa kuri Sawa Cars: {{title}} ku {{price}}',
            'forRent': 'Ikodeshwa',
            'certified': 'Yemejwe {{score}}/150',
            'safariReady': 'Yiteguye Safari',
            'unavailableUntil': 'Ntiyaboneka kugeza {{date}}',
            'availability': 'Ukuboneka & Gutumiza',
            'requestDates': 'Saba Amataliki yo Gukodesha',
            'availabilityNote': 'Ukuboneka kw\'imodoka kwemezwa n\'uwanditse imodoka ikodeshwa mu buryo bwigenga.',
            'pricing': 'Ibiciro byo Gukodesha',
            'dailyRate': 'Igiciro ku Munsi',
            'weeklyRate': 'Igiciro ku Cyumweru (iminsi 7+)',
            'saveVsDaily': 'Zigama {{amount}} ugereranyije n\'igiciro cy\'umunsi',
            'securityDeposit': 'Ingwate Isubizwa',
            'depositSub': 'Yishyurwa uwatanze imodoka mu gihe uyifashe, ikagarurwa nyuma yo gusuzuma imodoka uyigaruye.',
            'minRental': 'Igihe gito cyo gukodesha ni iminsi {{count}}.',
            'confirmTerms': 'Ibikubiye mu Bukode & Amabwiriza',
            'insurance': 'Ubwishingizi bwuzuye burimo',
            'roadside': 'Ubufasha mu muhanda 24/7',
            'mileageLimits': 'Ibirometero byagutse byemewe ku munsi',
            'depositTerms': 'Amabwiriza asobanutse yo gusubiza ingwate',
            'safetyLink': 'Soma amabwiriza y\'umutekano n\'amahame y\'abatanga serivisi',
            'inspectionTitle': 'Isuzuma Ryimbitse ry\'Amanota 150',
            'inspectionSub': 'Amanota yemejwe: {{score}}/150 • Imiterere yose yasuzumwe',
            'howItWorks': 'Uko Gukodesha Bikora',
            'step1Title': '1. Hitamo Amataliki & Ubaze',
            'step1Desc': 'Hitamo igihe ushaka gukodesha maze wohereze ubusabe bwo kumenya niba imodoka ihari.',
            'step2Title': '2. Emeza Amabwiriza & Suzuma',
            'step2Desc': 'Hura n\'uwatanze imodoka, mugenzure hamwe raporo y\'isuzuma rya mbere, mwemeze amasezerano.',
            'step3Title': '3. Twara Maze Uyigarure Neza',
            'step3Desc': 'Iryohereze urugendo rwawe mu Rwanda. Nugaruka, kora isuzuma ryo gusoza ngo usubizwe ingwate yawe.',
            'ctaDailyRental': 'Ubukode ku Munsi',
            'ctaPerDay': '/umunsi',
            'ctaRateNote': 'Lisansi n\'ingwate byishyurwa ukwabyo',
            'ctaInquiryOnly': 'Ubusabe Butaziguye',
            'ctaRequestAvailability': 'Baza Ukuboneka kw\'Imodoka',
        },
        'dutyCalculator': {
            'title': 'Kubara Imisoro ya RRA',
            'introTitle': 'Imisoro ya RRA ku Modoka Zitumizwa',
            'introSub': 'Imodoka nyinshi mu Rwanda ziva hanze. Iki gikoresho kigufasha kumenya igereranya ry\'imisoro yose wishyura Ikigo cy\'Imisoro n\'Amahoro (RRA).',
            'lastReviewed': 'Ibiciro biheruka gusuzumwa {{date}}.',
            'vehicleValue': 'Agaciro k\'imodoka (RWF)',
            'valuePlaceholder': 'urugero: 20000000',
            'valueHint': 'Injiza igiciro cyo kugura imodoka (agaciro ka FOB cyangwa CIF)',
            'engineDisplacement': 'Ubunini bwa moteri (cc)',
            'vehicleAge': 'Imyaka imodoka imaze',
            'calcBtn': 'Bara Imisoro yo Gutumiza',
            'dutyBreakdown': 'Ibisobanuro by\'Imisoro',
            'vehicleSummary': 'Imodoka ya {{val}}',
            'assessedValue': 'Agaciro kashyizweho umusoro (−{{pct}}% kubera imyaka)',
            'cifValue': 'Agaciro ka CIF (agaciro kemejwe + gutwara + ubwishingizi)',
            'dutiesApplied': 'IMISORO YASHYIZWEHO',
            'customsDuty': 'Umusoro wa gasutamo (25% bya CIF)',
            'exciseDuty': 'Umusoro w\'akarusho ({{rate}}% bya CIF + gasutamo)',
            'vat': 'TVA — {{rate}}% (kuri CIF + indi misoro)',
            'withholdingTax': 'Umusoro w\'ifatira ({{rate}}% bya CIF)',
            'infraLevy': 'Umusoro w\'ibikorwa remezo ({{rate}}% bya CIF)',
            'totalDuties': 'Yose Hamwe y\'Imisoro',
            'grandTotal': 'Amafaranga Yose Hamwe (imodoka + imisoro)',
            'effectiveRate': 'Igipimo nyakuri cy\'umusoro',
            'effectiveRateDesc': 'Ku gaciro k\'imodoka ka {{val}}, {{rate}}% yongerwaho nk\'umusoro wo kuyizana mu Rwanda.',
            'estimatedLandedCost': 'Igiciro cyose kugeza i Kigali',
            'rwfNote': 'Imibare yose iri mu mafaranga y\'u Rwanda (RWF)',
            'disclaimer': 'Iri ni igereranya rishingiye ku bipimo bisanzwe bya RRA byo muri 2026. Umusoro nyakuri ushobora guhinduka bitewe n\'imyaka y\'imodoka, igihugu yakozwemo, n\'isuzuma rya RRA. Gana umukozi wemewe wa gasutamo (clearing agent) kugira ngo umenye umusoro nyakuri.',
            'ageUnder2': 'Munsi y\'imyaka 2',
            'age2to4': 'Imyaka 2 – 4',
            'age4to6': 'Imyaka 4 – 6',
            'age6to8': 'Imyaka 6 – 8',
            'age8to10': 'Imyaka 8 – 10',
            'ageOver10': 'Hejuru y\'imyaka 10',
            'ccCity': 'Imodoka nto z\'umujyi',
            'ccSedan': 'Ikinyabiziga gisanzwe, crossover',
            'ccSuv': 'Imodoka nini ya SUV, luxury, V8+',
            'exciseBadge': 'Akarusho {{rate}}',
        },
        'financing': {
            'title': 'Kubara Inguzanyo y\'Imodoka',
            'introTitle': 'Gereranya ibyo wishyura ku kwezi',
            'introSub': 'Bishingiye ku nyungu z\'amabanki yo mu Rwanda muri 2026 ku nguzanyo z\'imodoka. Inyungu nyakuri zishobora guhinduka — vugana na banki yawe kugira ngo uguhe igiciro cya nyacyo.',
            'carPrice': 'Igiciro cy\'imodoka (RWF)',
            'carPricePlaceholder': 'urugero: 24000000',
            'downPayment': 'Amafaranga y\'intangiriro (RWF)',
            'downPaymentPlaceholder': 'urugero: 5000000 (20%)',
            'loanAmount': 'Ingano y\'inguzanyo',
            'loanTerm': 'Igihe cy\'inguzanyo',
            'compareBanks': 'Gereranya amabanki',
            'sortedByRate': 'urutonde kuva ku nyungu nto',
            'lowestRate': 'Inyungu nto cyane',
            'perYear': 'ku mwaka',
            'monthly': 'Ku kwezi',
            'totalInterest': 'Inyungu yose hamwe',
            'totalRepaid': 'Ayishyurwa yose hamwe',
            'yourEstimate': 'Igereranya ryawe · {{bank}}',
            'annualRate': 'Inyungu ku mwaka',
            'monthlyPayment': 'Ayishyurwa ku kwezi',
            'months': 'Amezi {{count}} (imyaka {{years}})',
            'disclaimer': 'Iri ni igereranya gusa. Inyungu nyakuri, amafaranga y\'inyongera n\'uburenganzira byiterwa n\'amateka yawe y\'inguzanyo, amabwiriza ya banki n\'imodoka wahisemo. Sawa Cars ntikora nk\'umuhuza w\'inguzanyo.',
            'bankBKNote': 'Banki nini kurusha izindi mu Rwanda',
            'bankEquityNote': 'Urusobe rwa banki muri Afurika',
            'bankIMNote': 'Inyungu ziciriritse ku modoka',
            'bankKCBNote': 'Banki ikomeye muri Afurika y\'Iburasirazuba',
        },
        'carValuation': {
            'title': 'Imodoka Yanjye Ihagaze Gute?',
            'lede': 'Bona igereranya ry\'igiciro cyo ku isoko ako kanya — ku buntu, nta konti ikenewe. Bifata amasegonda 30 gusa.',
            'make': 'Ubwoko bw\'Imodoka',
            'makePlaceholder': 'Andika ubwoko, urugero: Peugeot',
            'otherBrand': 'Ubundi bwoko',
            'model': 'Icyitegererezo (Model)',
            'modelPlaceholder': 'urugero: RAV4, Civic, Forester',
            'year': 'Umwaka yakozwemo',
            'mileage': 'Ibirometero yagenze (km)',
            'mileagePlaceholder': 'urugero: 45000',
            'checkingMarket': 'Kugenzura ku isoko…',
            'getValuation': 'Bona Agaciro k\'Imodoka',
            'fillRequired': 'Uzuza ubwoko, umwaka n\'ibirometero',
            'noAccountRequired': 'Nta konti ikenewe. Amakuru yawe arinzwe 100%.',
            'yourValuation': 'Agaciro k\'Imodoka Yawe',
            'estimatedMarketValue': 'AGACIRO NYAKURI KU ISOKO',
            'basedOnComparables': 'Bishingiye ku modoka {{count}} zisa z\'ubwoko bwa {{make}} ziri kuri Sawa Cars',
            'basedOnMarket': 'Bishingiye ku makuru y\'isoko rya Kigali ryo muri iki gihe',
            'getCertifiedPrice': 'Bona igiciro cyemejwe n\'inzobere',
            'certifiedPriceSub': 'Imodoka zitsinze isuzuma ryacu ry\'amanota 150 zigurishwa ku kigero kigera kuri 12% hejuru — kandi vuba inshuro 3.',
            'step1': 'Fata umwanya wo gusuzumisha imodoka ku kigo cya Sawa cyose',
            'step2': 'Itsinde isuzuma ry\'amanota 150 — tuyifotore maze tuyishyire ku isoko',
            'step3': 'Hura n\'abaguzi banyuze mu bugenzuzi, muhererekanye imodoka ku kigo cyacu',
            'submitForInspection': 'Yohereze Isuzumwe',
            'valueAnotherCar': 'Suzuma iyindi modoka',
            'notEnoughData': 'Ntidushoboye kubona igereranya muri aka kanya — nta makuru ahagije y\'isoko. Ongera ugerageze.',
        },
    },
    'fr': {
        'rentalDetail': {
            'seats': 'Places',
            'gearbox': 'Boîte de vitesses',
            'fuel': 'Carburant',
            'year': 'Année',
            'notFoundTitle': 'Véhicule de Location Introuvable',
            'notFoundSub': 'Cette annonce de location a peut-être expiré ou est actuellement indisponible.',
            'goBack': 'Retourner',
            'loading': 'Chargement des détails de la location…',
            'share': 'Partager la location',
            'shareMessage': 'Découvrez cette location sur Sawa Cars : {{title}} à {{price}}',
            'forRent': 'À Louer',
            'certified': 'Certifié {{score}}/150',
            'safariReady': 'Prêt pour Safari',
            'unavailableUntil': 'Indisponible jusqu\'au {{date}}',
            'availability': 'Disponibilité & Réservation',
            'requestDates': 'Demander les dates de location',
            'availabilityNote': 'La disponibilité est vérifiée et confirmée directement par le loueur indépendant.',
            'pricing': 'Tarifs de Location',
            'dailyRate': 'Tarif journalier',
            'weeklyRate': 'Tarif hebdomadaire (7+ jours)',
            'saveVsDaily': 'Économisez {{amount}} par rapport au tarif journalier',
            'securityDeposit': 'Dépôt de Garantie Remboursable',
            'depositSub': 'Payé directement au loueur lors de la prise en charge et remboursé après vérification du retour.',
            'minRental': 'La durée minimale de location est de {{count}} jours.',
            'confirmTerms': 'Inclusions & Conditions de Location',
            'insurance': 'Assurance tous risques incluse',
            'roadside': 'Assistance dépannage 24h/24 et 7j/7',
            'mileageLimits': 'Kilométrage quotidien généreux inclus',
            'depositTerms': 'Conditions claires et transparentes de restitution de caution',
            'safetyLink': 'Consultez nos normes de sécurité et de prestataires',
            'inspectionTitle': 'Contrôle Technique en 150 Points',
            'inspectionSub': 'Score certifié : {{score}}/150 • État complet vérifié',
            'howItWorks': 'Comment Fonctionne la Location',
            'step1Title': '1. Choisissez les dates et demandez',
            'step1Desc': 'Choisissez la durée souhaitée et envoyez une demande de disponibilité directement au loueur.',
            'step2Title': '2. Validez les conditions et inspectez',
            'step2Desc': 'Rencontrez le loueur, examinez le rapport d\'état des lieux numérique et validez le contrat de location.',
            'step3Title': '3. Roulez et restituez en toute sérénité',
            'step3Desc': 'Profitez de votre voyage au Rwanda. Au retour, complétez le contrôle de restitution pour libérer votre caution.',
            'ctaDailyRental': 'Location journalière',
            'ctaPerDay': '/jour',
            'ctaRateNote': 'Carburant et caution en sus',
            'ctaInquiryOnly': 'Demande Directe au Loueur',
            'ctaRequestAvailability': 'Demander la Disponibilité',
        },
        'dutyCalculator': {
            'title': 'Calculateur de Droits de Douane',
            'introTitle': 'Droits de Douane RRA au Rwanda',
            'introSub': 'La plupart des véhicules au Rwanda sont importés. Ce calculateur estime le montant total des taxes et droits dus à l\'Office Rwandais des Recettes (RRA).',
            'lastReviewed': 'Barèmes révisés le {{date}}.',
            'vehicleValue': 'Valeur du véhicule (RWF)',
            'valuePlaceholder': 'ex. 20000000',
            'valueHint': 'Entrez le prix d\'achat du véhicule (valeur FOB ou CIF)',
            'engineDisplacement': 'Cylindrée du moteur',
            'vehicleAge': 'Âge du véhicule',
            'calcBtn': 'Calculer les Droits de Douane',
            'dutyBreakdown': 'Détail des Droits et Taxes',
            'vehicleSummary': 'Véhicule de {{val}}',
            'assessedValue': 'Valeur imposable retenue (−{{pct}}% pour dépréciation)',
            'cifValue': 'Valeur CIF (valeur imposable + fret + assurance)',
            'dutiesApplied': 'TAXES ET DROITS APPLIQUÉS',
            'customsDuty': 'Droits de douane (25% de la valeur CIF)',
            'exciseDuty': 'Droit d\'accise ({{rate}}% de la valeur CIF + douane)',
            'vat': 'TVA — {{rate}}% (sur CIF + droits cumulés)',
            'withholdingTax': 'Retenue à la source ({{rate}}% de CIF)',
            'infraLevy': 'Redevance d\'infrastructure ({{rate}}% de CIF)',
            'totalDuties': 'Total des Droits et Taxes',
            'grandTotal': 'Coût Total Rendu (véhicule + taxes)',
            'effectiveRate': 'Taux effectif de taxation',
            'effectiveRateDesc': 'Sur la valeur du véhicule de {{val}}, {{rate}}% s\'ajoutent en taxes douanières pour importer ce véhicule au Rwanda.',
            'estimatedLandedCost': 'Coût de revient estimé à Kigali',
            'rwfNote': 'Tous les montants sont exprimés en francs rwandais (RWF)',
            'disclaimer': 'Cette estimation est calculée selon les barèmes officiels 2026 de l\'Office Rwandais des Recettes (RRA). Le montant réel peut varier selon l\'âge, l\'origine et l\'évaluation finale de la RRA. Consultez un transitaire agréé pour un calcul définitif.',
            'ageUnder2': 'Moins de 2 ans',
            'age2to4': '2 à 4 ans',
            'age4to6': '4 à 6 ans',
            'age6to8': '6 à 8 ans',
            'age8to10': '8 à 10 ans',
            'ageOver10': 'Plus de 10 ans',
            'ccCity': 'Citadines et petites berlines',
            'ccSedan': 'Berlines moyennes, crossovers',
            'ccSuv': 'Grands SUV, véhicules de luxe, V8+',
            'exciseBadge': 'Accise {{rate}}',
        },
        'financing': {
            'title': 'Calculateur de Financement',
            'introTitle': 'Estimez vos mensualités',
            'introSub': 'Basé sur les taux moyens des prêts automobiles des banques commerciales du Rwanda pour 2026. Les taux réels peuvent varier — contactez votre banque pour une offre personnalisée.',
            'carPrice': 'Prix du véhicule (RWF)',
            'carPricePlaceholder': 'ex. 24000000',
            'downPayment': 'Apport initial (RWF)',
            'downPaymentPlaceholder': 'ex. 5000000 (20%)',
            'loanAmount': 'Montant emprunté',
            'loanTerm': 'Durée du crédit',
            'compareBanks': 'Comparer les banques',
            'sortedByRate': 'trié par taux d\'intérêt',
            'lowestRate': 'Taux le plus bas',
            'perYear': 'par an',
            'monthly': 'Mensualité',
            'totalInterest': 'Intérêts totaux',
            'totalRepaid': 'Montant total remboursé',
            'yourEstimate': 'Votre estimation · {{bank}}',
            'annualRate': 'Taux d\'intérêt annuel',
            'monthlyPayment': 'Mensualité estimée',
            'months': '{{count}} mois ({{years}} ans)',
            'disclaimer': 'Cette simulation est purement indicative. Les taux définitifs, frais de dossier et conditions d\'octroi dépendent de votre profil d\'emprunteur et de l\'analyse bancaire. Sawa Cars n\'est pas un intermédiaire de crédit.',
            'bankBKNote': 'Première institution bancaire du Rwanda',
            'bankEquityNote': 'Réseau bancaire panafricain',
            'bankIMNote': 'Taux attractifs sur le crédit auto',
            'bankKCBNote': 'Groupe bancaire majeur d\'Afrique de l\'Est',
        },
        'carValuation': {
            'title': 'Quelle est la Valeur de Mon Véhicule ?',
            'lede': 'Obtenez une estimation immédiate de la valeur de marché — gratuit, sans inscription. En seulement 30 secondes.',
            'make': 'Marque',
            'makePlaceholder': 'Entrez la marque, ex. Peugeot',
            'otherBrand': 'Autre marque',
            'model': 'Modèle (optionnel)',
            'modelPlaceholder': 'ex. RAV4, Civic, Forester',
            'year': 'Année',
            'mileage': 'Kilométrage (km)',
            'mileagePlaceholder': 'ex. 45000',
            'checkingMarket': 'Analyse du marché en cours…',
            'getValuation': 'Obtenir mon Estimation',
            'fillRequired': 'Indiquez la marque, l\'année et le kilométrage',
            'noAccountRequired': 'Aucun compte requis. Vos informations restent strictement confidentielles.',
            'yourValuation': 'Votre Estimation de Valeur',
            'estimatedMarketValue': 'VALEUR MARCHANDE ESTIMÉE',
            'basedOnComparables': 'Basé sur {{count}} véhicules comparables de marque {{make}} sur Sawa Cars',
            'basedOnMarket': 'Basé sur les transactions récentes du marché de Kigali',
            'getCertifiedPrice': 'Vendez au meilleur prix certifié',
            'certifiedPriceSub': 'Les véhicules ayant validé notre contrôle en 150 points se vendent jusqu\'à 12% plus cher — et 3 fois plus rapidement.',
            'step1': 'Réservez un créneau d\'inspection gratuit dans l\'un de nos centres Sawa',
            'step2': 'Passez le contrôle en 150 points — nous réalisons le shooting photo professionnel et publions l\'annonce',
            'step3': 'Rencontrez des acheteurs vérifiés et finalisez la cession en toute sécurité dans nos centres',
            'submitForInspection': 'Soumettre pour Inspection',
            'valueAnotherCar': 'Estimer un autre véhicule',
            'notEnoughData': 'Données de marché insuffisantes pour ce modèle actuellement. Veuillez réessayer ultérieurement.',
        },
    },
    'sw': {
        'rentalDetail': {
            'seats': 'Viti',
            'gearbox': 'Gia',
            'fuel': 'Mafuta',
            'year': 'Mwaka',
            'notFoundTitle': 'Gari la Kukodisha Halipatikani',
            'notFoundSub': 'Tangazo hili la ukodishaji huenda limeisha muda wake au halipatikani kwa sasa.',
            'goBack': 'Rudi Nyuma',
            'loading': 'Inapakia maelezo ya ukodishaji…',
            'share': 'Shiriki ukodishaji',
            'shareMessage': 'Angalia gari hili la kukodisha kwenye Sawa Cars: {{title}} kwa {{price}}',
            'forRent': 'Linakodishwa',
            'certified': 'Limethibitishwa {{score}}/150',
            'safariReady': 'Tayari kwa Safari',
            'unavailableUntil': 'Haipatikani hadi {{date}}',
            'availability': 'Upatikanaji & Uhifadhi',
            'requestDates': 'Omba Tarehe za Ukodishaji',
            'availabilityNote': 'Upatikanaji unathibitishwa moja kwa moja na mtoa huduma huru wa ukodishaji.',
            'pricing': 'Viwango vya Ukodishaji',
            'dailyRate': 'Kiwango cha Kila Siku',
            'weeklyRate': 'Kiwango cha Wiki (siku 7+)',
            'saveVsDaily': 'Okoa {{amount}} ukilinganisha na kiwango cha siku',
            'securityDeposit': 'Amana ya Usalama Inayorudishwa',
            'depositSub': 'Inalipwa moja kwa moja kwa mtoa huduma wakati wa kuchukua gari na inarudishwa baada ya ukaguzi wa kurudi.',
            'minRental': 'Kipindi cha chini cha kukodisha ni siku {{count}}.',
            'confirmTerms': 'Vitu Vilivyojumuishwa & Masharti',
            'insurance': 'Bima kamili imejumuishwa',
            'roadside': 'Msaada wa dharura barabarani 24/7',
            'mileageLimits': 'Kiwango kizuri cha kilomita kwa siku',
            'depositTerms': 'Masharti wazi ya kurejeshewa amana',
            'safetyLink': 'Soma viwango vyetu vya usalama na watoa huduma',
            'inspectionTitle': 'Ukaguzi wa Kiufundi wa Pointi 150',
            'inspectionSub': 'Alama iliyothibitishwa: {{score}}/150 • Hali kamili imethibitishwa',
            'howItWorks': 'Jinsi Ukodishaji Unavyofanya Kazi',
            'step1Title': '1. Chagua Tarehe & Omba',
            'step1Desc': 'Chagua muda wako unaopendelea wa kukodisha na utume ombi la upatikanaji moja kwa moja kwa mtoa huduma.',
            'step2Title': '2. Thibitisha Masharti & Kagua',
            'step2Desc': 'Kutana na mtoa huduma, kagua ripoti ya kidijitali ya ukaguzi wa mwanzo na uthibitishe mkataba wa ukodishaji.',
            'step3Title': '3. Endesha & Rudisha kwa Usalama',
            'step3Desc': 'Furahia safari yako kote nchini Rwanda. Unaporudi, kamilisha ukaguzi wa kurudisha ili kurejeshewa amana yako.',
            'ctaDailyRental': 'Ukodishaji wa Kila Siku',
            'ctaPerDay': '/siku',
            'ctaRateNote': 'Mafuta na amana ni ziada',
            'ctaInquiryOnly': 'Ombi la Moja kwa Moja',
            'ctaRequestAvailability': 'Omba Upatikanaji',
        },
        'dutyCalculator': {
            'title': 'Kikokotoo cha Ushuru wa Forodha',
            'introTitle': 'Ushuru wa Forodha wa RRA Rwanda',
            'introSub': 'Magari mengi nchini Rwanda huagizwa kutoka nje. Kikokotoo hiki kinakadiria jumla ya ushuru, ada na kodi inayolipwa kwa Mamlaka ya Mapato ya Rwanda (RRA).',
            'lastReviewed': 'Viwango vilivyopitiwa mara ya mwisho tarehe {{date}}.',
            'vehicleValue': 'Thamani ya gari (RWF)',
            'valuePlaceholder': 'mfano: 20000000',
            'valueHint': 'Weka bei ya ununuzi wa gari (thamani ya FOB au CIF)',
            'engineDisplacement': 'Ukubwa wa injini (cc)',
            'vehicleAge': 'Umri wa gari',
            'calcBtn': 'Kokotoa Ushuru wa Kuagiza',
            'dutyBreakdown': 'Mchanganuo wa Ushuru',
            'vehicleSummary': 'Gari la thamani ya {{val}}',
            'assessedValue': 'Thamani iliyotathminiwa kwa kodi (−{{pct}}% kwa umri)',
            'cifValue': 'Thamani ya CIF (thamani iliyotathminiwa + usafirishaji + bima)',
            'dutiesApplied': 'USHURU NA KODI ZILIZOTOZWA',
            'customsDuty': 'Ushuru wa forodha (25% ya CIF)',
            'exciseDuty': 'Ushuru wa bidhaa maalum ({{rate}}% ya CIF + forodha)',
            'vat': 'VAT — {{rate}}% (kwa CIF + ushuru)',
            'withholdingTax': 'Kodi ya zuio ({{rate}}% ya CIF)',
            'infraLevy': 'Ushuru wa miundombinu ({{rate}}% ya CIF)',
            'totalDuties': 'Jumla ya Ushuru Wote',
            'grandTotal': 'Jumla Kuu (gari + ushuru)',
            'effectiveRate': 'Kiwango halisi cha ushuru',
            'effectiveRateDesc': 'Kati ya thamani ya gari ya {{val}}, {{rate}}% inaongezwa kama ushuru wa kuingiza gari hili nchini Rwanda.',
            'estimatedLandedCost': 'Gharama iliyokadiriwa ya kufika Kigali',
            'rwfNote': 'Nambari zote zinaonyeshwa kwa Faranga za Rwanda (RWF)',
            'disclaimer': 'Huu ni makadirio kulingana na viwango rasmi vya Mamlaka ya Mapato ya Rwanda (RRA) vya mwaka 2026. Ushuru halisi unaweza kutofautiana kulingana na umri wa gari, nchi lilikotoka na tathmini ya RRA. Wasiliana na wakala aliyeidhinishwa wa forodha kwa hesabu kamili.',
            'ageUnder2': 'Chini ya miaka 2',
            'age2to4': 'Miaka 2 – 4',
            'age4to6': 'Miaka 4 – 6',
            'age6to8': 'Miaka 6 – 8',
            'age8to10': 'Miaka 8 – 10',
            'ageOver10': 'Zaidi ya miaka 10',
            'ccCity': 'Magari madogo ya mjini',
            'ccSedan': 'Magari ya kawaida ya sedan, crossovers',
            'ccSuv': 'Magari makubwa ya SUV, anasa, V8+',
            'exciseBadge': 'Bidhaa maalum {{rate}}',
        },
        'financing': {
            'title': 'Kikokotoo cha Mkopo wa Gari',
            'introTitle': 'Kadiria malipo ya kila mwezi',
            'introSub': 'Kulingana na viwango vya riba vya mikopo ya magari vya benki za biashara nchini Rwanda vya mwaka 2026. Viwango halisi vinaweza kutofautiana — wasiliana na benki yako kwa ofa rasmi.',
            'carPrice': 'Bei ya gari (RWF)',
            'carPricePlaceholder': 'mfano: 24000000',
            'downPayment': 'Malipo ya awali (RWF)',
            'downPaymentPlaceholder': 'mfano: 5000000 (20%)',
            'loanAmount': 'Kiasi cha mkopo',
            'loanTerm': 'Muda wa mkopo',
            'compareBanks': 'Linganisha benki',
            'sortedByRate': 'imepangwa kwa kiwango cha riba',
            'lowestRate': 'Riba ya chini kabisa',
            'perYear': 'kwa mwaka',
            'monthly': 'Kila mwezi',
            'totalInterest': 'Jumla ya riba',
            'totalRepaid': 'Jumla itakayolipwa',
            'yourEstimate': 'Makadirio yako · {{bank}}',
            'annualRate': 'Kiwango cha riba kwa mwaka',
            'monthlyPayment': 'Malipo ya kila mwezi',
            'months': 'Miezi {{count}} (miaka {{years}})',
            'disclaimer': 'Huu ni makadirio tu. Viwango halisi, ada na vigezo vya kustahiki hutegemea rekodi yako ya kifedha, sera za benki na gari husika. Sawa Cars haitoi mikopo.',
            'bankBKNote': 'Benki kubwa zaidi nchini Rwanda',
            'bankEquityNote': 'Mtandao wa benki kote Afrika',
            'bankIMNote': 'Viwango vya ushindani vya mikopo ya magari',
            'bankKCBNote': 'Benki inayoongoza Afrika Mashariki',
        },
        'carValuation': {
            'title': 'Gari Langu Lina Thamani Gani?',
            'lede': 'Pata makadirio ya papo hapo ya thamani sokoni — bure, huhitaji akaunti. Inachukua sekunde 30 tu.',
            'make': 'Aina ya Gari (Make)',
            'makePlaceholder': 'Andika aina, mfano: Peugeot',
            'otherBrand': 'Aina nyingine',
            'model': 'Mfano (Model)',
            'modelPlaceholder': 'mfano: RAV4, Civic, Forester',
            'year': 'Mwaka',
            'mileage': 'Umbali uliotembea (km)',
            'mileagePlaceholder': 'mfano: 45000',
            'checkingMarket': 'Inachambua soko…',
            'getValuation': 'Pata Thamani ya Gari',
            'fillRequired': 'Jaza aina, mwaka na umbali',
            'noAccountRequired': 'Huhitaji kufungua akaunti. Maelezo yako ni siri kamili.',
            'yourValuation': 'Thamani ya Gari Lako',
            'estimatedMarketValue': 'THAMANI ILIYOKADIRIWA SOKONI',
            'basedOnComparables': 'Kulingana na magari {{count}} yanayofanana ya {{make}} kwenye Sawa Cars',
            'basedOnMarket': 'Kulingana na takwimu za sasa za soko la Kigali',
            'getCertifiedPrice': 'Pata bei iliyothibitishwa',
            'certifiedPriceSub': 'Magari yanayofaulu ukaguzi wetu wa pointi 150 huuzwa kwa hadi 12% zaidi — na mara 3 kwa haraka zaidi.',
            'step1': 'Weka nafasi ya ukaguzi wa bure katika kituo chochote cha Sawa',
            'step2': 'Faulu ukaguzi wa pointi 150 — tunalipiga picha kitaalamu na kuliweka sokoni',
            'step3': 'Kutana na wanunuzi waliothibitishwa na ukabidhi gari katika kituo chetu',
            'submitForInspection': 'Wasilisha kwa Ukaguzi',
            'valueAnotherCar': 'Kadiria gari lingine',
            'notEnoughData': 'Hatukuweza kukadiria kwa sasa — hakuna data ya kutosha ya soko. Jaribu tena.',
        },
    },
    'ko': {
        'rentalDetail': {
            'seats': '탑승 인원',
            'gearbox': '변속기',
            'fuel': '연료',
            'year': '연식',
            'notFoundTitle': '렌트 차량을 찾을 수 없습니다',
            'notFoundSub': '해당 렌트 매물이 만료되었거나 현재 이용할 수 없습니다.',
            'goBack': '뒤로 가기',
            'loading': '렌트 상세 정보 불러오는 중…',
            'share': '렌트 공유',
            'shareMessage': 'Sawa Cars에서 이 렌트 차량을 확인해 보세요: {{title}} {{price}}',
            'forRent': '렌트 가능',
            'certified': '인증 완료 {{score}}/150',
            'safariReady': '사파리 투어 맞춤형',
            'unavailableUntil': '{{date}}까지 이용 불가',
            'availability': '예약 가능 여부 & 일정',
            'requestDates': '렌트 일정 문의하기',
            'availabilityNote': '예약 가능 여부는 독립 렌터카 제공업체에서 직접 확인 및 승인합니다.',
            'pricing': '대여 요금 안내',
            'dailyRate': '일일 대여 요금',
            'weeklyRate': '주간 요금 (7일 이상)',
            'saveVsDaily': '일일 요금 대비 {{amount}} 절약',
            'securityDeposit': '환불 가능한 보증금',
            'depositSub': '차량 픽업 시 제공업체에 직접 지불하며, 반납 점검 완료 후 전액 환불됩니다.',
            'minRental': '최소 렌트 기간은 {{count}}일입니다.',
            'confirmTerms': '포함 사항 및 렌트 규정',
            'insurance': '종합 차량 보험 기본 포함',
            'roadside': '24시간 연중무휴 긴급출동 지원',
            'mileageLimits': '넉넉한 일일 주행거리 기본 제공',
            'depositTerms': '투명하고 명확한 보증금 환불 규정',
            'safetyLink': '마켓플레이스 안전 및 제공업체 운영 기준 확인',
            'inspectionTitle': '150가지 항목 정밀 성능 점검',
            'inspectionSub': '인증 점수: {{score}}/150점 • 전반적인 차량 상태 점검 완료',
            'howItWorks': '렌트 이용 절차',
            'step1Title': '1. 일정 선택 및 문의',
            'step1Desc': '원하는 렌트 기간을 선택하고 제공업체에 직접 예약 가능 여부를 문의합니다.',
            'step2Title': '2. 계약 조건 확인 및 차량 점검',
            'step2Desc': '제공업체를 직접 만나 디지털 차량 상태 점검표를 확인하고 렌트 계약을 체결합니다.',
            'step3Title': '3. 편안한 주행 및 신속한 반납',
            'step3Desc': '르완다 전역을 편리하게 운행하세요. 반납 시 최종 점검을 완료하면 보증금이 반환됩니다.',
            'ctaDailyRental': '일일 대여 요금',
            'ctaPerDay': '/일',
            'ctaRateNote': '유류비 및 보증금 별도',
            'ctaInquiryOnly': '제공업체 직접 예약 문의',
            'ctaRequestAvailability': '예약 가능 여부 문의',
        },
        'dutyCalculator': {
            'title': '수입 관세 계산기',
            'introTitle': '르완다 국세청(RRA) 차량 수입 관세',
            'introSub': '르완다 내 대부분의 차량은 해외에서 수입됩니다. 이 계산기는 르완다 국세청(RRA)에 납부해야 하는 관세, 개별소비세, 부가세 및 제반 세금을 추산합니다.',
            'lastReviewed': '최근 세율 검토일: {{date}}.',
            'vehicleValue': '차량 가액 (RWF)',
            'valuePlaceholder': '예: 20000000',
            'valueHint': '차량 구매 가격을 입력하세요 (FOB 또는 CIF 가액)',
            'engineDisplacement': '엔진 배기량',
            'vehicleAge': '차량 연식/차령',
            'calcBtn': '수입 관세 계산하기',
            'dutyBreakdown': '관세 및 제세공과금 내역',
            'vehicleSummary': '차량 가액 {{val}}',
            'assessedValue': '과세 표준 평가액 (차령 감가상각 −{{pct}}% 반영)',
            'cifValue': 'CIF 가액 (과세 표준액 + 운임 + 보험료)',
            'dutiesApplied': '적용 세목 및 부과 내역',
            'customsDuty': '기본 관세 (CIF의 25%)',
            'exciseDuty': '개별소비세 (CIF + 관세의 {{rate}}%)',
            'vat': '부가가치세 — {{rate}}% (CIF + 관세/소비세 합산액)',
            'withholdingTax': '원천징수세 (CIF의 {{rate}}%)',
            'infraLevy': '인프라 개발 분담금 (CIF의 {{rate}}%)',
            'totalDuties': '총 납부 세액 합계',
            'grandTotal': '총 인수 비용 (차량 가액 + 총 세액)',
            'effectiveRate': '실효 관세율',
            'effectiveRateDesc': '차량 가액 {{val}} 기준으로, 르완다 반입 시 약 {{rate}}%의 수입 관세 및 세금이 추가됩니다.',
            'estimatedLandedCost': '키갈리 도착 기준 예상 총비용',
            'rwfNote': '모든 금액은 르완다 프랑(RWF) 기준입니다.',
            'disclaimer': '본 계산 결과는 2026년 르완다 국세청(RRA) 표준 세율을 바탕으로 한 추정치입니다. 실제 세액은 차량 연식, 수입 원산지 및 국세청 최종 실사에 따라 달라질 수 있습니다. 정확한 세액 산정은 공인 관세사와 상담하세요.',
            'ageUnder2': '2년 미만',
            'age2to4': '2년 ~ 4년',
            'age4to6': '4년 ~ 6년',
            'age6to8': '6년 ~ 8년',
            'age8to10': '8년 ~ 10년',
            'ageOver10': '10년 초과',
            'ccCity': '경차 및 소형 해치백',
            'ccSedan': '일반 세단, 크로스오버',
            'ccSuv': '중대형 SUV, 고급차, V8 이상',
            'exciseBadge': '소비세 {{rate}}',
        },
        'financing': {
            'title': '자동차 할부 금융 계산기',
            'introTitle': '월 예상 납입금 조회',
            'introSub': '2026년 르완다 시중은행 자동차 대출 금리를 기준으로 산출되었습니다. 실제 금리는 상이할 수 있으므로 정확한 견적은 거래 은행에 문의하세요.',
            'carPrice': '차량 가격 (RWF)',
            'carPricePlaceholder': '예: 24000000',
            'downPayment': '선납금/선수금 (RWF)',
            'downPaymentPlaceholder': '예: 5000000 (20%)',
            'loanAmount': '총 대출 신청 금액',
            'loanTerm': '대출 상환 기간',
            'compareBanks': '금융사별 금리 비교',
            'sortedByRate': '최저 금리순 정렬',
            'lowestRate': '최저 금리',
            'perYear': '연',
            'monthly': '월 납입금',
            'totalInterest': '총 납부 이자',
            'totalRepaid': '총 상환 원리금',
            'yourEstimate': '선택 견적 산출 결과 · {{bank}}',
            'annualRate': '연이율',
            'monthlyPayment': '월 상환액',
            'months': '{{count}}개월 ({{years}}년)',
            'disclaimer': '본 산출 금액은 단순 추정치입니다. 실제 승인 금리, 수수료 및 대출 가능 여부는 고객 신용도, 은행 심사 기준 및 대상 차량에 따라 결정됩니다. Sawa Cars는 직접 대출을 취급하거나 중개하지 않습니다.',
            'bankBKNote': '르완다 최대 시중은행',
            'bankEquityNote': '범아프리카 금융 네트워크',
            'bankIMNote': '경쟁력 있는 오토론 금리 제공',
            'bankKCBNote': '동아프리카 선도 금융 그룹',
        },
        'carValuation': {
            'title': '내 차 시세 조회',
            'lede': '회원가입 없이 30초 만에 현재 시장 시세를 무료로 확인해 보세요.',
            'make': '제조사/브랜드',
            'makePlaceholder': '제조사 입력 (예: Peugeot)',
            'otherBrand': '기타 브랜드',
            'model': '모델명 (선택)',
            'modelPlaceholder': '예: RAV4, Civic, Forester',
            'year': '연식',
            'mileage': '주행거리 (km)',
            'mileagePlaceholder': '예: 45000',
            'checkingMarket': '실시간 시장 시세 분석 중…',
            'getValuation': '내 차 시세 확인하기',
            'fillRequired': '제조사, 연식, 주행거리를 입력해 주세요',
            'noAccountRequired': '로그인이 필요 없습니다. 개인정보는 안전하게 보호됩니다.',
            'yourValuation': '차량 시세 평가 결과',
            'estimatedMarketValue': '예상 시장 거래 시세',
            'basedOnComparables': 'Sawa Cars에 등록된 {{count}}대의 유사 {{make}} 매물 기반',
            'basedOnMarket': '키갈리 실시간 거래 데이터 기반',
            'getCertifiedPrice': '공식 인증 매물로 최고가 판매하기',
            'certifiedPriceSub': '150가지 항목 정밀 성능 점검을 통과한 차량은 일반 매물 대비 최대 12% 더 높은 가격에 3배 빠르게 판매됩니다.',
            'step1': '가까운 Sawa 인증 센터에 무료 점검 일정을 예약합니다',
            'step2': '150가지 성능 점검을 거친 후 전문 스튜디오 촬영 및 매물 등록이 진행됩니다',
            'step3': '인증된 실제 구매자와 Sawa 센터에서 안전하게 직거래를 완료합니다',
            'submitForInspection': '성능 점검 신청하기',
            'valueAnotherCar': '다른 차량 시세 조회',
            'notEnoughData': '현재 시장 데이터가 부족하여 시세를 산출할 수 없습니다. 잠시 후 다시 시도해 주세요.',
        },
    },
    'zh': {
        'rentalDetail': {
            'seats': '座位数',
            'gearbox': '变速箱',
            'fuel': '燃油类型',
            'year': '出厂年份',
            'notFoundTitle': '未找到该租赁车辆',
            'notFoundSub': '该车辆租赁信息可能已下架或当前不可用。',
            'goBack': '返回上一页',
            'loading': '正在加载租赁详情…',
            'share': '分享租赁信息',
            'shareMessage': '在 Sawa Cars 查看此精选租赁车源：{{title}}，租金：{{price}}',
            'forRent': '可租赁',
            'certified': '官方认证 {{score}}/150',
            'safariReady': '适合长途越野/野外游览',
            'unavailableUntil': '直到 {{date}} 前不可用',
            'availability': '可用排期与预订',
            'requestDates': '申请租赁日期',
            'availabilityNote': '车辆实际可用性由独立租车服务商直接核对并确认。',
            'pricing': '租赁费用明细',
            'dailyRate': '日租金',
            'weeklyRate': '周租优惠价（7天及以上）',
            'saveVsDaily': '对比日租价立省 {{amount}}',
            'securityDeposit': '可退还押金',
            'depositSub': '取车时直接支付给车队服务商，还车验收无损后原路退还。',
            'minRental': '最低起租期限为 {{count}} 天。',
            'confirmTerms': '租赁包含服务与条款',
            'insurance': '包含全额商业机动车保险',
            'roadside': '24/7 全天候道路紧急救援',
            'mileageLimits': '包含充足的每日免费行驶里程',
            'depositTerms': '透明公正的押金退还细则',
            'safetyLink': '阅读平台交易安全与服务商保障规范',
            'inspectionTitle': '150项官方专业技术检测',
            'inspectionSub': '官方认证得分：{{score}}/150 • 整车车况全方位核验',
            'howItWorks': '租车服务流程',
            'step1Title': '1. 选定日期并提交咨询',
            'step1Desc': '挑选心仪的租赁时长，并直接向车队服务商发起档期确认。',
            'step2Title': '2. 确认合同条款并现场验车',
            'step2Desc': '与服务商面对面接洽，复核电子交接验车单并签署正规租赁合同。',
            'step3Title': '3. 安心自驾与顺畅交还',
            'step3Desc': '畅享在卢旺达的美好旅程。还车时完成快速复验即可轻松退还押金。',
            'ctaDailyRental': '按日计费',
            'ctaPerDay': '/天',
            'ctaRateNote': '不含燃油费及押金',
            'ctaInquiryOnly': '直连服务商确认',
            'ctaRequestAvailability': '申请预订档期',
        },
        'dutyCalculator': {
            'title': '进口关税计算器',
            'introTitle': '卢旺达税局 (RRA) 车辆进口关税',
            'introSub': '卢旺达境内的绝大多数汽车均通过海外进口。本计算器可精准测算需向卢旺达税务总局 (RRA) 缴纳的海关关税、消费税、增值税及各项综合税费。',
            'lastReviewed': '税率基准最近复核日期：{{date}}。',
            'vehicleValue': '车辆货值 (RWF)',
            'valuePlaceholder': '例如：20000000',
            'valueHint': '请输入车辆采购价格（FOB 或 CIF 申报价值）',
            'engineDisplacement': '发动机排量',
            'vehicleAge': '车辆出厂年限/车龄',
            'calcBtn': '计算进口关税总额',
            'dutyBreakdown': '各项税费明细清单',
            'vehicleSummary': '车辆申报价值 {{val}}',
            'assessedValue': '关税计税评估价（按车龄折旧扣减 −{{pct}}%）',
            'cifValue': '到岸 CIF 价（评估计税价 + 国际运费 + 保险费）',
            'dutiesApplied': '适用的税费项目清单',
            'customsDuty': '基本海关关税（CIF 的 25%）',
            'exciseDuty': '特种消费税（CIF + 关税总额的 {{rate}}%）',
            'vat': '增值税 — {{rate}}%（以 CIF + 各项关税为基数）',
            'withholdingTax': '预扣所得税（CIF 的 {{rate}}%）',
            'infraLevy': '基础设施建设附加税（CIF 的 {{rate}}%）',
            'totalDuties': '应缴税费总额',
            'grandTotal': '完税落地总成本（车价 + 全部税费）',
            'effectiveRate': '综合实际关税税率',
            'effectiveRateDesc': '按照车辆申报价值 {{val}} 计算，将该车辆进口至卢旺达需额外缴纳约 {{rate}}% 的进口税费。',
            'estimatedLandedCost': '基加利落地预估总成本',
            'rwfNote': '所有金额均以卢旺达法郎 (RWF) 计算显示',
            'disclaimer': '本结果系依据 2026 年卢旺达税务局 (RRA) 标准法定义务税率估算。实际清关税费可能会因车龄、原产地及海关实物核定而有所差异。如需最终确定税单，请向具有资质的报关行咨询。',
            'ageUnder2': '2年以内',
            'age2to4': '2至4年',
            'age4to6': '4至6年',
            'age6to8': '6至8年',
            'age8to10': '8至10年',
            'ageOver10': '10年以上',
            'ccCity': '微型/城市两厢轿车',
            'ccSedan': '主流三厢轿车、紧凑型跨界车',
            'ccSuv': '中大型 SUV、高端豪华车、V8及以上',
            'exciseBadge': '消费税率 {{rate}}',
        },
        'financing': {
            'title': '汽车金融贷款分期计算器',
            'introTitle': '测算每月还款金额',
            'introSub': '依据 2026 年卢旺达主流商业银行汽车贷款利率基准测算。实际利率以各银行最终批复为准 — 欢迎向您的开户银行索取正式贷款方案。',
            'carPrice': '车辆售价 (RWF)',
            'carPricePlaceholder': '例如：24000000',
            'downPayment': '首付款金额 (RWF)',
            'downPaymentPlaceholder': '例如：5000000 (20%)',
            'loanAmount': '实际贷款总额',
            'loanTerm': '分期贷款期限',
            'compareBanks': '主流商业银行利率对比',
            'sortedByRate': '按年化利率由低到高排列',
            'lowestRate': '最优低利率',
            'perYear': '年化',
            'monthly': '每月还款',
            'totalInterest': '利息支出总额',
            'totalRepaid': '本息合计还款总额',
            'yourEstimate': '贷款方案测算结果 · {{bank}}',
            'annualRate': '年化执行利率',
            'monthlyPayment': '每月应还金额',
            'months': '{{count}} 个月（{{years}}年）',
            'disclaimer': '本计算结果仅供参考。实际贷款利率、手续费率及批复额度取决于您的个人资信状况、各银行信贷政策及抵押车辆情况。Sawa Cars 本身不直接发放贷款。',
            'bankBKNote': '卢旺达规模最大的商业银行',
            'bankEquityNote': '泛非金融网络银行',
            'bankIMNote': '汽车贷款利率极具市场竞争力',
            'bankKCBNote': '东非地区领先金融巨头',
        },
        'carValuation': {
            'title': '智能车辆估价',
            'lede': '30 秒即刻获取真实市场行情估价 — 完全免费，无需注册账户。',
            'make': '车辆品牌',
            'makePlaceholder': '输入品牌名称，例如：Peugeot',
            'otherBrand': '其他品牌',
            'model': '车辆型号（选填）',
            'modelPlaceholder': '例如：RAV4, Civic, Forester',
            'year': '出厂年份',
            'mileage': '行驶里程 (km)',
            'mileagePlaceholder': '例如：45000',
            'checkingMarket': '正在分析全网交易行情…',
            'getValuation': '获取权威市场估价',
            'fillRequired': '请完整填写品牌、年份与行驶里程',
            'noAccountRequired': '无需登录账号。我们严格保护您的个人隐私。',
            'yourValuation': '车辆估价报告',
            'estimatedMarketValue': '预估合理市场交易价值',
            'basedOnComparables': '基于 Sawa Cars 平台上 {{count}} 辆同款 {{make}} 真实交易数据',
            'basedOnMarket': '基于当前基加利全网二手车交易行情',
            'getCertifiedPrice': '申请官方认证溢价出售',
            'certifiedPriceSub': '通过 150 项官方专业检测的认证车辆，平均成交溢价高达 12% — 成交速度提升 3 倍。',
            'step1': '免费在线预约前往就近的 Sawa 官方检测中心',
            'step2': '完成 150 项专业检测 — 官方摄影师为您拍摄全景车况大片并全网发布',
            'step3': '直面高意向实名认证买家，在官方服务中心安心完成线下交付',
            'submitForInspection': '预约官方上牌检测',
            'valueAnotherCar': '估价其他车辆',
            'notEnoughData': '当前该车型市场交易样本不足，暂无法生成精准估价。请稍后重试。',
        },
    }
}

ALL_DICTS = {
    'en': (DICT_EN, 'dict_en.py'),
    'rw': (DICT_RW, 'dict_rw.py'),
    'fr': (DICT_FR, 'dict_fr.py'),
    'sw': (DICT_SW, 'dict_sw.py'),
    'ko': (DICT_KO, 'dict_ko.py'),
    'zh': (DICT_ZH, 'dict_zh.py'),
}

for lang_code, (base_dict, filename) in ALL_DICTS.items():
    add = ADDITIONS[lang_code]
    for section_name, section_keys in add.items():
        if section_name not in base_dict:
            base_dict[section_name] = {}
        base_dict[section_name].update(section_keys)
    
    # Save back to file
    dict_var = f'DICT_{lang_code.upper()}'
    filepath = os.path.join(os.path.dirname(__file__), 'i18n_data', filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f'# {filename}\n')
        f.write(f'{dict_var} = ')
        pprint.pprint(base_dict, stream=f, indent=2, width=120, sort_dicts=True)
        f.write('\n')
    print(f'Successfully updated {filename}')

print('All 6 dictionaries updated successfully!')
