/// <reference types="next" />
/// <reference types="next/image-types/global" />

// Why this file exists.
//
// The `*.jpeg` / `*.png` module declarations that make `import hero from
// '@/assets/marketing/hero.jpeg'` type-check come from Next's
// `next/image-types/global`, which is normally pulled in by `next-env.d.ts`.
// That file is generated by `next build` / `next dev` and is gitignored, so it
// does not exist in a clean checkout — which is exactly what CI has when it
// runs `tsc --noEmit` BEFORE `npm run build`. Result: TS2307 "Cannot find
// module '@/assets/marketing/hero-sedan-studio.jpeg'" on every run, on a
// codebase that type-checks perfectly on any machine that has ever built it.
//
// Referencing the same types from a committed file fixes it without touching
// the generated one. `/// <reference>` is idempotent, so this coexists with
// next-env.d.ts rather than duplicating its declarations — and unlike that
// file, it points at nothing under .next/, so it is valid before a build.
